import path from "node:path";
import { createHash } from "node:crypto";
import { createReadStream, createWriteStream } from "node:fs";
import fs from "node:fs/promises";
import { once } from "node:events";
import { Readable } from "node:stream";
import { pipeline } from "node:stream/promises";
import type { ReadableStream as NodeReadableStream } from "node:stream/web";
import { expectedChunkSize } from "@/lib/chunking";
import { getEnv } from "@/lib/env";

/*
 * The filesystem security boundary (PRD §11.1, CONTEXT §7.1).
 *
 * Every filesystem operation in this application goes through this module. No
 * route handler calls `fs` directly — a bare `fs.readdir(userInput)` anywhere
 * else is an automatic PR rejection (CONTEXT §2 item 2), because the moment
 * path resolution exists in two places, only one of them gets audited.
 *
 * What this module does NOT do, deliberately:
 *
 *   - It does not percent-decode. Query strings arrive already decoded by the
 *     URL layer; decoding again here would turn `%252e%252e%252f` into `../`
 *     and hand an attacker the escape this module exists to prevent.
 *   - It does not consult the database. `Tool.filePath` is re-validated through
 *     `resolveWithinRoot` on every download (PRD §9.4 step 2) — the DB is not
 *     a trusted source of paths.
 */

export type PathErrorCode = "INVALID_PATH" | "PATH_OUTSIDE_ROOT" | "NOT_FOUND" | "NOT_A_DIRECTORY" | "EACCES";

export class PathError extends Error {
  constructor(
    readonly code: PathErrorCode,
    msg: string,
  ) {
    super(msg);
    this.name = "PathError";
  }
}

/** PRD §9.3 step 1. Longer than any real path; a 5000-char string is an attack, not a filename. */
const MAX_PATH_LENGTH = 4096;

/** PRD §9.3: directory listings are capped, with a flag, rather than streaming 200k entries into a modal. */
const MAX_ENTRIES = 5000;

/** Chunk temp storage. Never listed — it is internal, and PRD §14 requires it stay invisible. */
const INTERNAL_UPLOAD_DIR = ".uploads";

let rootCache: { configured: string; real: string } | null = null;

/**
 * The storage root, fully resolved. Cached per configured value, so a test that
 * repoints `STORAGE_ROOT` gets the new root without a bespoke reset hook.
 */
export async function getRoot(): Promise<string> {
  const configured = getEnv().STORAGE_ROOT;
  if (rootCache?.configured === configured) return rootCache.real;

  const real = await fs.realpath(configured);
  rootCache = { configured, real };
  return real;
}

/**
 * Resolve a client-supplied relative path to an absolute path guaranteed to sit
 * under STORAGE_ROOT. This is the choke point every attack in PRD §11.1 has to
 * get through.
 *
 * The target must exist; use `resolveForWrite` for a path being created.
 */
export async function resolveWithinRoot(relative: string): Promise<string> {
  const root = await getRoot();
  const target = joinWithinRoot(root, relative);

  // realpath is what defeats symlinks — a string check cannot see through one.
  let real: string;
  try {
    real = await fs.realpath(target);
  } catch (error) {
    throw fromFsError(error, relative);
  }

  assertContained(real, root);
  return real;
}

/**
 * Resolve a path that does not exist yet — an upload's destination file.
 *
 * The parent directory must exist and must be inside the root; the basename is
 * then appended. Resolving the parent is what matters: if the parent is a
 * symlink pointing outside the root, `realpath` sees it and this rejects.
 *
 * Not in the original issue scope, but uploads need it (issues 28 and 30), and
 * the alternative is upload code hand-rolling its own path logic outside the
 * one module that gets audited.
 */
export async function resolveForWrite(relative: string): Promise<string> {
  const root = await getRoot();
  const target = joinWithinRoot(root, relative);

  const parent = path.dirname(target);
  const base = path.basename(target);

  if (base === "" || base === "." || base === "..") {
    throw new PathError("INVALID_PATH", "Path does not name a file");
  }

  let realParent: string;
  try {
    realParent = await fs.realpath(parent);
  } catch (error) {
    throw fromFsError(error, relative);
  }

  assertContained(realParent, root);

  const resolved = path.join(realParent, base);
  assertContained(resolved, root);
  return resolved;
}

/**
 * Create `STORAGE_ROOT/.uploads/<uploadId>/` (PRD §9.5, issue 28) and return its
 * absolute path, for storing on the `Upload.tempDir` column.
 *
 * `.uploads` itself is created alongside it, `recursive: true`, so a fresh
 * `STORAGE_ROOT` provisioned without it does not need a manual step first. Both
 * directories are `0700`: chunk parts are readable only by the process that
 * wrote them.
 *
 * `uploadId` is never client-supplied — it is generated by the init route
 * before this is called — but it still goes through `resolveForWrite` rather
 * than a bare `path.join`, because "trusted input" and "validated input" should
 * never quietly become the same claim in a module whose whole job is validation
 * (CONTEXT §2 item 2).
 */
export async function createUploadDir(uploadId: string): Promise<string> {
  const root = await getRoot();
  await fs.mkdir(path.join(root, INTERNAL_UPLOAD_DIR), { recursive: true, mode: 0o700 });

  const dir = await resolveForWrite(`${INTERNAL_UPLOAD_DIR}/${uploadId}`);
  await fs.mkdir(dir, { recursive: true, mode: 0o700 });
  return dir;
}

/**
 * Remove an upload's temp directory (PRD §9.5: cancel, complete, and the
 * janitor all end here). Tolerant of it already being gone — `force: true` —
 * since every caller may race a previous cleanup of the same directory.
 *
 * The one check this keeps, even though every caller's `absolute` comes from
 * an `Upload.tempDir` column this module itself wrote: a hand-edited or
 * corrupted row must not turn a cleanup job into `rm -rf` on an arbitrary path
 * (CONTEXT §2 item 2 again — the boundary does not get to trust its own
 * output just because it usually wrote it).
 *
 * `path.resolve` first, not a bare string comparison — `assertContained` (the
 * same containment check every other path in this module uses) only defeats a
 * smuggled `..` if the segments have already been collapsed. A literal
 * `<root>/.uploads/x/../../../etc` string *starts with* `<root>/.uploads/`
 * while resolving to well outside it; comparing the raw string would have let
 * a corrupted `tempDir` walk out of the upload root entirely.
 */
export async function removeUploadDir(absolute: string): Promise<void> {
  const root = await getRoot();
  const uploadsRoot = path.join(root, INTERNAL_UPLOAD_DIR);
  const resolved = path.resolve(absolute);

  assertContained(resolved, uploadsRoot);
  await fs.rm(resolved, { recursive: true, force: true });
}

/**
 * Write one upload chunk into `<tempDir>/<index>.part` (PRD §9.5, CONTEXT §7.3,
 * issue 29). Streams straight through with `pipeline()` — never buffered, so a
 * 16 MiB chunk never becomes 16 MiB of resident memory (CONTEXT §2 item 3).
 *
 * Writes to `<index>.part.tmp` and renames only after `pipeline()` resolves.
 * If the client aborts mid-chunk, `pipeline()` rejects, the `.tmp` file is left
 * behind (or removed, best-effort) and the rename never happens — so a short
 * write can never be mistaken for a complete `.part` the caller then marks
 * received.
 *
 * `tempDir` and `index` are not re-validated here: `tempDir` is the caller's
 * `Upload.tempDir` column (itself only ever produced by `createUploadDir`), and
 * `index` must already be an integer the route handler bounded against
 * `totalChunks` — a validated integer's string form contains only digits, so it
 * cannot carry a path separator regardless.
 */
export async function writeUploadChunk(
  tempDir: string,
  index: number,
  body: ReadableStream,
): Promise<number> {
  const tmpPath = path.join(tempDir, `${index}.part.tmp`);
  const finalPath = path.join(tempDir, `${index}.part`);

  try {
    await pipeline(Readable.fromWeb(body as unknown as NodeReadableStream), createWriteStream(tmpPath));
  } catch (error) {
    await fs.rm(tmpPath, { force: true });
    throw error;
  }

  const stat = await fs.stat(tmpPath);
  await fs.rename(tmpPath, finalPath);
  return stat.size;
}

// --- upload completion (PRD §9.5, issue 30) -----------------------------------

export class MissingChunkError extends Error {
  constructor(readonly index: number) {
    super(`Chunk ${index} was never received.`);
    this.name = "MissingChunkError";
  }
}

export class ChunkSizeMismatchError extends Error {
  constructor(readonly index: number, readonly expected: number, readonly actual: number) {
    super(`Chunk ${index} is ${actual} bytes on disk, expected ${expected}.`);
    this.name = "ChunkSizeMismatchError";
  }
}

export class SizeMismatchError extends Error {
  constructor(readonly expected: number, readonly actual: number) {
    super(`Assembled ${actual} bytes, expected ${expected}.`);
    this.name = "SizeMismatchError";
  }
}

/**
 * The cheap pre-flight before the expensive concatenation pass: every part
 * file exists and is exactly the size its index implies (the last part may be
 * short). `stat`-only — never reads a byte of content, so a client that
 * dropped chunk 4 of 500 fails in milliseconds, not after re-reading the
 * 499 chunks it did send.
 */
export async function verifyUploadParts(
  tempDir: string,
  totalChunks: number,
  chunkSize: number,
  totalSize: bigint,
): Promise<void> {
  for (let index = 0; index < totalChunks; index++) {
    const expected = expectedChunkSize(index, totalChunks, chunkSize, Number(totalSize));

    let stat;
    try {
      stat = await fs.stat(path.join(tempDir, `${index}.part`));
    } catch {
      throw new MissingChunkError(index);
    }
    if (stat.size !== expected) {
      throw new ChunkSizeMismatchError(index, expected, stat.size);
    }
  }
}

/**
 * Ensure `STORAGE_ROOT/<UPLOAD_SUBDIR>/<targetSubdir?>` exists and pick the
 * absolute destination for `fileName` inside it — suffixing `" (2)"`, `" (3)"`,
 * … on a name collision unless `overwrite` is set (PRD §9.5). Nothing is
 * written to `fileName` itself here; this only decides where it will go.
 *
 * `targetSubdir` is client-supplied (issue 30's "watch out"). The directory
 * does not exist yet, so `resolveWithinRoot` cannot validate it — `mkdir`
 * would need to run first, and running it on a raw join would let `../../etc`
 * walk out of the root before there is anything to check `realpath` against.
 * `joinWithinRoot` (the same `..`-neutralising choke point every other write
 * path in this module goes through) anchors it first; `realpath` plus
 * `assertContained` re-confirms containment on what `mkdir` actually created,
 * the same defence-in-depth `resolveForWrite` applies to a file's parent.
 */
export async function resolveUploadDestination(
  fileName: string,
  targetSubdir: string | undefined,
  overwrite: boolean,
): Promise<{ absolutePath: string; fileName: string }> {
  const root = await getRoot();
  const subdirRelative = path.posix.join(getEnv().UPLOAD_SUBDIR, targetSubdir ?? "");
  const dirTarget = joinWithinRoot(root, subdirRelative);

  await fs.mkdir(dirTarget, { recursive: true });
  const realDir = await fs.realpath(dirTarget);
  assertContained(realDir, root);

  return uniqueDestination(realDir, fileName, overwrite);
}

async function uniqueDestination(
  dir: string,
  fileName: string,
  overwrite: boolean,
): Promise<{ absolutePath: string; fileName: string }> {
  if (overwrite || !(await pathExists(path.join(dir, fileName)))) {
    return { absolutePath: path.join(dir, fileName), fileName };
  }

  const ext = path.extname(fileName);
  const base = fileName.slice(0, fileName.length - ext.length);

  // Bounded, like `admin-tools.ts`'s slug suffixing: a name colliding 200
  // times is a script hammering this endpoint, not a real filename to solve for.
  for (let n = 2; n < 200; n++) {
    const candidateName = `${base} (${n})${ext}`;
    const candidatePath = path.join(dir, candidateName);
    if (!(await pathExists(candidatePath))) {
      return { absolutePath: candidatePath, fileName: candidateName };
    }
  }

  throw new PathError("INVALID_PATH", "Too many filename collisions in this folder");
}

async function pathExists(absolute: string): Promise<boolean> {
  try {
    await fs.access(absolute);
    return true;
  } catch {
    return false;
  }
}

/**
 * Concatenate `<tempDir>/0.part .. <totalChunks-1>.part`, in index order, into
 * `destAbsolute` — one read of the data, hashing as it goes (CONTEXT §7.3), not
 * a second pass once the file is assembled.
 *
 * Writes to `<destAbsolute>.tmp`. Renamed into place only if the byte count
 * written matches `expectedSize`; on a mismatch the `.tmp` file is removed and
 * `SizeMismatchError` is thrown, but `tempDir` — the original chunk parts — is
 * left untouched, so an admin can inspect what actually arrived (PRD §9.5).
 * The caller decides when it is safe to `removeUploadDir(tempDir)`: only after
 * this resolves.
 */
export async function concatenateUpload(
  tempDir: string,
  totalChunks: number,
  destAbsolute: string,
  expectedSize: bigint,
): Promise<{ size: bigint; checksum: string }> {
  const tmpPath = `${destAbsolute}.tmp`;
  const hash = createHash("sha256");
  let size = 0;

  const dest = createWriteStream(tmpPath);
  try {
    for (let index = 0; index < totalChunks; index++) {
      const part = createReadStream(path.join(tempDir, `${index}.part`));
      for await (const chunk of part as AsyncIterable<Buffer>) {
        hash.update(chunk);
        size += chunk.length;
        if (!dest.write(chunk)) {
          await once(dest, "drain");
        }
      }
    }
    dest.end();
    await once(dest, "finish");
  } catch (error) {
    dest.destroy();
    await fs.rm(tmpPath, { force: true });
    throw error;
  }

  if (size !== Number(expectedSize)) {
    await fs.rm(tmpPath, { force: true });
    throw new SizeMismatchError(Number(expectedSize), size);
  }

  await fs.rename(tmpPath, destAbsolute);
  return { size: BigInt(size), checksum: hash.digest("hex") };
}

/**
 * Streamed SHA-256 over an already-registered tool's file (PRD §11.3,
 * issue 32). Re-validates the stored path first, like every other absolute
 * path this module is handed — the DB is not a trusted source of paths
 * (PRD §9.4 step 2) — rather than trusting that a caller already checked it.
 */
export async function hashFile(absolute: string): Promise<string> {
  const real = await resolveStoredPath(absolute);
  const hash = createHash("sha256");
  await pipeline(createReadStream(real), hash);
  return hash.digest("hex");
}

/**
 * Re-validate an **absolute** path already stored in the database (PRD §9.4
 * step 2: "the DB is not trusted").
 *
 * Distinct from `resolveWithinRoot`, which anchors a *client-supplied relative*
 * path at the root. Do not reach this by relativising and re-resolving: the
 * stored path may contain a symlinked prefix that the root's realpath does not
 * — `/var` vs `/private/var` on macOS is the everyday example — and
 * `path.relative` between the two produces a `../../..` escape that then fails
 * to resolve. Realpath both sides and compare, which is what this does.
 *
 * Errors name only the basename; the caller already has the row, and the full
 * host path must not reach a log line that might be surfaced (CONTEXT §2 item 5).
 */
export async function resolveStoredPath(absolute: string): Promise<string> {
  if (absolute.includes("\0")) {
    throw new PathError("INVALID_PATH", "Invalid stored path");
  }
  if (absolute.length > MAX_PATH_LENGTH) {
    throw new PathError("INVALID_PATH", "Stored path too long");
  }

  const root = await getRoot();

  let real: string;
  try {
    real = await fs.realpath(absolute);
  } catch (error) {
    throw fromFsError(error, path.basename(absolute));
  }

  assertContained(real, root);
  return real;
}

/** Absolute path -> path relative to the root, for sending to the client. */
export async function toRelative(absolute: string): Promise<string> {
  return path.relative(await getRoot(), absolute);
}

/**
 * Whether an already-registered `Tool.filePath` still resolves to a readable
 * regular file (PRD §11.3, issue 33) — the read-only twin of `resolveStoredPath`
 * for the integrity sweep, which needs a boolean to act on rather than a
 * PathError to interpret. Never throws, and touches nothing on disk beyond the
 * `stat` itself.
 */
export async function fileStillExists(absolute: string): Promise<boolean> {
  try {
    const real = await resolveStoredPath(absolute);
    const stat = await fs.stat(real);
    return stat.isFile();
  } catch {
    return false;
  }
}

export interface DirectoryEntry {
  name: string;
  type: "dir" | "file";
  /** Bytes as a decimal string for files (BigInt boundary), null for directories. */
  size: string | null;
  mtime: string;
  ext?: string;
}

export interface DirectoryListing {
  path: string;
  parent: string | null;
  entries: DirectoryEntry[];
  truncated: boolean;
}

/**
 * List a directory under the root (PRD §9.3 steps 6–7).
 *
 * `.uploads` is filtered here rather than at the call site — a caller that
 * forgets is a caller that exposes chunk temp files, and there is exactly one
 * place to forget if the filter lives here.
 */
export async function listDirectory(
  relative = "",
  options: { showHidden?: boolean } = {},
): Promise<DirectoryListing> {
  const { showHidden = false } = options;

  const root = await getRoot();
  const dir = await resolveWithinRoot(relative);

  const stat = await lstatOrThrow(dir, relative);
  if (!stat.isDirectory()) {
    throw new PathError("NOT_A_DIRECTORY", "Path is not a directory");
  }

  let dirents;
  try {
    dirents = await fs.readdir(dir, { withFileTypes: true });
  } catch (error) {
    throw fromFsError(error, relative);
  }

  const truncated = dirents.length > MAX_ENTRIES;
  const entries: DirectoryEntry[] = [];

  for (const dirent of dirents.slice(0, MAX_ENTRIES)) {
    const entry = await describeEntry(dir, dirent.name, root, showHidden);
    if (entry !== null) entries.push(entry);
  }

  entries.sort(compareEntries);

  const normalized = await toRelative(dir);
  return {
    path: normalized,
    parent: normalized === "" ? null : path.dirname(normalized) === "." ? "" : path.dirname(normalized),
    entries,
    truncated,
  };
}

export interface FileStat {
  /** Path relative to the root — never the absolute host path. */
  path: string;
  name: string;
  size: bigint;
  mtime: Date;
}

/** Stat a regular file under the root. Directories are rejected, not described. */
export async function statFile(relative: string): Promise<FileStat> {
  const resolved = await resolveWithinRoot(relative);
  const stat = await lstatOrThrow(resolved, relative);

  if (!stat.isFile()) {
    throw new PathError("INVALID_PATH", "Path is not a regular file");
  }

  return {
    path: await toRelative(resolved),
    name: path.basename(resolved),
    size: BigInt(stat.size),
    mtime: stat.mtime,
  };
}

/* ============================================================================
 * THE ONLY CODE IN THIS PRODUCT THAT DELETES A FILE.
 *
 * PRD §14 requires that no scheduled job anywhere in this repo removes a file
 * from STORAGE_ROOT, and §16 D4 makes "never auto-delete" a product decision,
 * not a default. Deletion happens only here, only when an admin explicitly asks
 * for it (`DELETE /api/admin/tools/[id]?deleteFile=true`), and this function has
 * exactly one caller — `deleteTool` in `lib/admin-tools.ts`. If a second caller
 * ever appears, that is the thing to argue about in review.
 *
 * Three refusals, all of them from PRD §8.2:
 *
 *   1. **Outside the root.** The stored path is re-resolved and re-contained.
 *      `Tool.filePath` is data in a database, not a trusted value; a row edited
 *      by hand, restored from an old backup, or written before the root moved
 *      must not be able to point `unlink` at `/etc`.
 *
 *   2. **A symlink.** Checked with `lstat` on the path *as stored*, before any
 *      `realpath`. This is the case containment alone cannot catch: a symlink
 *      living inside the root whose target is also inside the root passes every
 *      containment test, and unlinking it silently destroys the link while the
 *      admin believes they deleted the artifact.
 *
 *      Note when this can actually fire. Registration resolves through
 *      `resolveWithinRoot`, which realpaths — so a tool registered *via* a
 *      symlink stores the target's real path, and the link was only ever how
 *      the admin addressed the file. A stored path that is still a symlink
 *      therefore means the row has stopped describing what it described: edited
 *      by hand, restored from an older backup, or a file swapped for a link on
 *      disk after the fact. Refusing is right even when the target is innocent,
 *      because in every one of those cases a human should look first.
 *
 *   3. **Not a regular file.** A directory, socket, or device node under the
 *      root is not an artifact this hub registered, and `unlink` on one is
 *      never what was meant.
 *
 * The "another Tool row references this path" refusal is deliberately NOT here:
 * it needs the database, and this module does not consult the database (see the
 * header). `deleteTool` performs that check before calling in.
 * ========================================================================== */
export async function deleteStoredFile(absolute: string): Promise<void> {
  const real = await assertDeletable(absolute);

  try {
    await fs.unlink(real);
  } catch (error) {
    throw fromFsError(error, path.basename(absolute));
  }
}

/**
 * The two refusals above that a *stored* path can fail before `deleteTool`'s
 * own "shared by another row" check even runs. Split out so the delete-
 * confirmation dialog can ask "would this be refused?" (`checkDeletable`)
 * without it drifting from what an actual deletion enforces (`deleteStoredFile`)
 * — one rule, two callers, per issue 25's "watch out".
 */
async function assertDeletable(absolute: string): Promise<string> {
  // Re-resolve through the same choke point every read path uses. Throws
  // PATH_OUTSIDE_ROOT, NOT_FOUND, or EACCES exactly as a download would.
  const real = await resolveStoredPath(absolute);

  // lstat the path *as stored* — realpath has already followed any symlink, so
  // asking `real` whether it is a link would always answer no.
  const link = await lstatOrThrow(absolute, path.basename(absolute));
  if (link.isSymbolicLink()) {
    throw new PathError("INVALID_PATH", "Refusing to delete a symlink; remove the link by hand");
  }
  if (!link.isFile()) {
    throw new PathError("INVALID_PATH", "Refusing to delete something that is not a regular file");
  }

  return real;
}

export interface DeletabilityCheck {
  eligible: boolean;
  /** A one-line, client-safe reason (PRD §8.2) — null when eligible. */
  reason: string | null;
}

/**
 * A non-throwing preview of `assertDeletable`, for the delete dialog's
 * server-decided radio option (PRD §8.2, issue 25). Every `PathError` this can
 * throw is already client-safe (`lib/api.ts`'s `apiFailure` says why), so its
 * message doubles as the reason shown in the UI.
 */
export async function checkDeletable(absolute: string): Promise<DeletabilityCheck> {
  try {
    await assertDeletable(absolute);
    return { eligible: true, reason: null };
  } catch (error) {
    if (error instanceof PathError) {
      return { eligible: false, reason: error.message };
    }
    throw error;
  }
}

// --- internals ---------------------------------------------------------------

/**
 * PRD §9.3 steps 1–3: reject the obviously hostile, then neutralise leading `..`
 * before resolution.
 *
 * `normalize("/" + p).slice(1)` is the trick: anchoring at `/` makes `../../etc`
 * collapse to `etc` rather than climbing out, so the subsequent `resolve` cannot
 * be walked above the root by the string alone.
 */
function joinWithinRoot(root: string, relative: string): string {
  if (relative.includes("\0")) {
    throw new PathError("INVALID_PATH", "Invalid path");
  }
  if (relative.length > MAX_PATH_LENGTH) {
    throw new PathError("INVALID_PATH", "Path too long");
  }

  // Backslashes are folded to separators, per CONTEXT §7.1.
  //
  // Be clear about what this does and does not buy on this deployment: on Linux
  // a backslash is a legal filename character, so `..\..\windows\system32` is
  // already just one harmless segment that resolves inside the root and 404s.
  // Removing this line fails no test. It is kept as defence for the case where
  // the root ever sits on a filesystem that treats `\` as a separator — not
  // because it is currently load-bearing. The cost is that a POSIX file whose
  // name genuinely contains a backslash becomes unaddressable, which is fine.
  const safeRelative = path.normalize("/" + relative.replace(/\\/g, "/")).slice(1);
  return path.resolve(root, safeRelative);
}

/**
 * The containment check. `real === root ||` plus `path.sep` is load-bearing:
 * a bare `startsWith(root)` accepts `/srv/downloads-evil`, which is a sibling
 * directory an attacker may well be able to create.
 */
function assertContained(candidate: string, root: string): void {
  if (candidate !== root && !candidate.startsWith(root + path.sep)) {
    throw new PathError("PATH_OUTSIDE_ROOT", "Path is outside the storage root");
  }
}

async function lstatOrThrow(absolute: string, relative: string) {
  try {
    return await fs.lstat(absolute);
  } catch (error) {
    throw fromFsError(error, relative);
  }
}

/**
 * Translate an fs error without leaking it. The raw message contains the
 * absolute host path (CONTEXT §2 item 5, PRD §11.2), so only the relative path
 * the caller already knows is echoed back.
 */
function fromFsError(error: unknown, relative: string): PathError {
  const code = (error as NodeJS.ErrnoException | undefined)?.code;

  if (code === "EACCES" || code === "EPERM") {
    return new PathError("EACCES", `Permission denied reading "${relative || "storage"}"`);
  }
  if (code === "ENOTDIR") {
    return new PathError("NOT_A_DIRECTORY", "Path is not a directory");
  }
  if (code === "ENAMETOOLONG") {
    return new PathError("INVALID_PATH", "Path too long");
  }
  return new PathError("NOT_FOUND", "Path does not exist");
}

/**
 * Describe one directory entry, or null if it must not be listed.
 *
 * Symlinks are followed only to decide whether they escape: one pointing outside
 * the root is skipped entirely rather than reported, so the listing cannot be
 * used to probe for the existence of files elsewhere on the host.
 */
async function describeEntry(
  dir: string,
  name: string,
  root: string,
  showHidden: boolean,
): Promise<DirectoryEntry | null> {
  if (name === INTERNAL_UPLOAD_DIR) return null;
  if (!showHidden && name.startsWith(".")) return null;

  const absolute = path.join(dir, name);

  let stat;
  try {
    stat = await fs.lstat(absolute);
  } catch {
    return null; // vanished between readdir and lstat; not worth failing the listing
  }

  if (stat.isSymbolicLink()) {
    let real: string;
    try {
      real = await fs.realpath(absolute);
    } catch {
      return null; // broken symlink
    }
    if (real !== root && !real.startsWith(root + path.sep)) return null;

    try {
      stat = await fs.stat(absolute);
    } catch {
      return null;
    }
  }

  if (stat.isDirectory()) {
    return { name, type: "dir", size: null, mtime: stat.mtime.toISOString() };
  }
  if (!stat.isFile()) {
    return null; // sockets, fifos, devices — not distributable artifacts
  }

  return {
    name,
    type: "file",
    size: BigInt(stat.size).toString(),
    mtime: stat.mtime.toISOString(),
    ext: path.extname(name).toLowerCase() || undefined,
  };
}

const collator = new Intl.Collator("en", { numeric: true, sensitivity: "base" });

/** Directories first, then files, each alphabetical (PRD §8.4). */
function compareEntries(a: DirectoryEntry, b: DirectoryEntry): number {
  if (a.type !== b.type) return a.type === "dir" ? -1 : 1;
  return collator.compare(a.name, b.name);
}
